# SPDX-License-Identifier: Apache-2.0
#
# Writes OUT with the git revision of SRC, for the extension to report as
# _core.__git_commit__ and _core.__git_dirty__:
#
#   cmake -DSRC=<repo> -DOUT=<header> -DGIT=<git executable> -P git_stamp.cmake
#
# Run on every build, not once at configure time: a rebuild after a commit must
# not carry the previous commit's stamp. The header is rewritten only when its
# content changes, so an unchanged tree does not recompile the extension.
#
# "Dirty" means tracked files differ from HEAD. Untracked files do not count —
# a local scratch file is not a change to the code that ran.

set(commit "unknown")
set(dirty 0)
if(GIT AND EXISTS "${SRC}/.git")
    execute_process(COMMAND "${GIT}" rev-parse HEAD
                    WORKING_DIRECTORY "${SRC}"
                    RESULT_VARIABLE rc
                    OUTPUT_VARIABLE out
                    OUTPUT_STRIP_TRAILING_WHITESPACE
                    ERROR_QUIET)
    if(rc EQUAL 0 AND out)
        set(commit "${out}")
        execute_process(COMMAND "${GIT}" status --porcelain --untracked-files=no
                        WORKING_DIRECTORY "${SRC}"
                        OUTPUT_VARIABLE st
                        OUTPUT_STRIP_TRAILING_WHITESPACE
                        ERROR_QUIET)
        if(st)
            set(dirty 1)
        endif()
    endif()
endif()

set(text "// Generated by python/git_stamp.cmake at build time. Do not edit.\n#define MOOTATION_GIT_COMMIT \"${commit}\"\n#define MOOTATION_GIT_DIRTY ${dirty}\n")
set(old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" old)
endif()
if(NOT "${old}" STREQUAL "${text}")
    file(WRITE "${OUT}" "${text}")
endif()
