// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// pybind11 module `mootation`.
//
// The algorithm table is NOT written out here. It is generated from
// include/mootation/algorithms.def — the same X-macro the test suite iterates over — so a
// new algorithm becomes callable from Python by adding the one line it already
// needs, and the binding cannot silently fall behind the library. CI fails if a
// header is missing from that file.
//
// Every core exposes set_seed/setup/step, but the tuning knobs differ per
// algorithm: only 19 of the 58 have set_t_max, 10 have set_T, 6 have set_kappa.
// Rather than a per-algorithm dispatch, each optional setter is detected with
// SFINAE and applied only where it exists. A knob the caller sets that the
// chosen algorithm does not have is REPORTED, not ignored — silently dropping
// it is how a run ends up not being the run you configured.
//
// Objectives are evaluated by a Python callback. That crosses the GIL once per
// batch, so use `evaluate_batch` for anything non-trivial.
// ============================================================================

#include <algorithm>
#include <atomic>
#include <climits>
#include <memory>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>

#include <pybind11/functional.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

#include <mootation/mootation.hpp>

// Generated by python/git_stamp.cmake on every build; absent when the module is
// built some other way, and then the revision is simply "unknown".
#if __has_include("mootation_git_stamp.h")
#include "mootation_git_stamp.h"
#endif
#ifndef MOOTATION_GIT_COMMIT
#define MOOTATION_GIT_COMMIT "unknown"
#endif
#ifndef MOOTATION_GIT_DIRTY
#define MOOTATION_GIT_DIRTY 0
#endif

namespace py = pybind11;

namespace {

// ── The problem, as configured from Python ─────────────────────────────────
struct PyProblem {
    std::vector<std::pair<double, double>> bounds;
    int    n_objectives = 2;
    int    n_limits     = 0;
    // One of the two. evaluate_batch is preferred: it crosses the GIL once per
    // generation instead of once per individual.
    std::function<std::vector<double>(std::vector<double>)>               evaluate;
    std::function<std::vector<std::vector<double>>(
        std::vector<std::vector<double>>)>                                evaluate_batch;
    // Optional; must return one row of limits per individual, same convention
    // as the C++ side: <= 0 satisfied, > 0 is the violation.
    std::function<std::vector<std::vector<double>>(
        std::vector<std::vector<double>>)>                                limits_batch;
};

// The active problem for the current run. A raw pointer is enough because a run
// is single-threaded from Python's side and the pointer outlives the vault.
PyProblem* g_problem = nullptr;

// Evaluations spent by the current run, counted where the Python evaluator is
// actually called: one per individual through eval_into, the batch size through
// py_run_batch. A warm start plants objectives without evaluating and costs
// nothing. Atomic because the step loop reads it with the GIL released.
std::atomic<long long> g_evaluations{0};

// Objective/limit evaluation, shared by every generated Problem<> below.
inline void eval_into(const std::vector<double>& vars,
                      std::vector<double>&       objs,
                      std::vector<double>&       lims)
{
    if (!g_problem) throw std::runtime_error("mootation: no active problem");
    py::gil_scoped_acquire gil;

    if (g_problem->evaluate_batch) {
        auto out = g_problem->evaluate_batch({vars});
        if (out.empty()) throw std::runtime_error("evaluate_batch returned nothing");
        objs = out.front();
    } else if (g_problem->evaluate) {
        objs = g_problem->evaluate(vars);
    } else {
        throw std::runtime_error("set problem.evaluate or problem.evaluate_batch");
    }
    ++g_evaluations;
    if (static_cast<int>(objs.size()) != g_problem->n_objectives)
        throw std::runtime_error("the evaluator returned the wrong number of objectives");

    if (g_problem->n_limits > 0) {
        if (!g_problem->limits_batch)
            throw std::runtime_error("n_limits > 0 requires problem.limits_batch");
        auto lim = g_problem->limits_batch({vars});
        if (lim.empty()) throw std::runtime_error("limits_batch returned nothing");
        lims = lim.front();
        if (static_cast<int>(lims.size()) != g_problem->n_limits)
            throw std::runtime_error("limits_batch returned the wrong width");
    }
}

// The BatchExecutor installed when the caller supplied evaluate_batch: the
// whole dirty set crosses the GIL in ONE call, which is what "batched
// evaluation" promises. Without it DataVault falls back to calc_objs one
// individual at a time and a batch function only ever sees single rows.
void py_run_batch(const mootation::BatchRequest& req, mootation::BatchResponse& resp)
{
    if (!g_problem) throw std::runtime_error("mootation: no active problem");
    py::gil_scoped_acquire gil;

    auto out = g_problem->evaluate_batch(req.variables);
    if (out.size() != req.size())
        throw std::runtime_error(
            "evaluate_batch returned " + std::to_string(out.size()) +
            " rows for a batch of " + std::to_string(req.size()));
    for (const auto& row : out)
        if (static_cast<int>(row.size()) != g_problem->n_objectives)
            throw std::runtime_error("the evaluator returned the wrong number of objectives");
    g_evaluations += static_cast<long long>(req.size());
    resp.objectives = std::move(out);

    if (g_problem->n_limits > 0) {
        if (!g_problem->limits_batch)
            throw std::runtime_error("n_limits > 0 requires problem.limits_batch");
        auto lim = g_problem->limits_batch(req.variables);
        if (lim.size() != req.size())
            throw std::runtime_error(
                "limits_batch returned " + std::to_string(lim.size()) +
                " rows for a batch of " + std::to_string(req.size()));
        for (const auto& row : lim)
            if (static_cast<int>(row.size()) != g_problem->n_limits)
                throw std::runtime_error("limits_batch returned the wrong width");
        resp.limits = std::move(lim);
    } else {
        resp.limits.clear();
    }
}

} // namespace

// Each algorithm needs ITS OWN individual type — crEA reads .cluster/.rank,
// NSGA-II reads .rank/.crowding_distance — so one tag per algorithm is
// generated from the same X-macro that drives the dispatch. The Problem<>
// specialization has to be written out in full: Based_Individual befriends
// Problem<T> only, so nothing else may touch ind.variables/objectives/limits.
#define MOOTATION_PY_PROBLEM(TAG, BASE)                                        \
    namespace { struct TAG : public mootation::BASE {}; }                      \
    namespace mootation {                                                      \
    template <>                                                                \
    class Problem<TAG> {                                                       \
    public:                                                                    \
        std::vector<std::pair<std::optional<double>, std::optional<double>>>   \
            bounds;                                                            \
        int get_vars_n() const { return static_cast<int>(bounds.size()); }     \
        int get_bin_vars_n() const { return 0; }                               \
        int get_objs_n() const                                                 \
        {                                                                      \
            return g_problem ? g_problem->n_objectives : 0;                    \
        }                                                                      \
        int get_lims_n() const                                                 \
        {                                                                      \
            return g_problem ? g_problem->n_limits : 0;                        \
        }                                                                      \
        void calc_objs(TAG& ind) const                                         \
        {                                                                      \
            eval_into(ind.variables, ind.objectives, ind.limits);              \
        }                                                                      \
    };                                                                         \
    }

#define MOOTATION_ALG(KEY, IND, CORE) MOOTATION_PY_PROBLEM(PyTag_##KEY, IND)
#include "mootation/algorithms.def"
#undef MOOTATION_ALG

namespace {

// ── Optional-setter detection ───────────────────────────────────────────────
// One macro per knob: a trait that asks "does this core have set_X(T)?", and an
// apply() that calls it when it does and reports when it does not.
#define MOOTATION_OPTIONAL_SETTER(NAME, SETTER, TYPE)                          \
    template <typename C, typename = void>                                     \
    struct has_##NAME : std::false_type {};                                    \
    template <typename C>                                                      \
    struct has_##NAME<C, std::void_t<decltype(std::declval<C&>().SETTER(       \
                             std::declval<TYPE>()))>> : std::true_type {};     \
    template <typename C>                                                      \
    bool apply_##NAME(C& core, TYPE v)                                         \
    {                                                                          \
        if constexpr (has_##NAME<C>::value) { core.SETTER(v); return true; }    \
        else { (void)core; (void)v; return false; }                            \
    }

MOOTATION_OPTIONAL_SETTER(t_max,      set_t_max,             int)
MOOTATION_OPTIONAL_SETTER(eta_c,      set_eta_crossover,     double)
MOOTATION_OPTIONAL_SETTER(eta_m,      set_eta_mutation,      double)
MOOTATION_OPTIONAL_SETTER(pc,         set_pc,                double)
MOOTATION_OPTIONAL_SETTER(pm,         set_pm,                double)
MOOTATION_OPTIONAL_SETTER(T,          set_T,                 int)
MOOTATION_OPTIONAL_SETTER(delta,      set_delta,             double)
MOOTATION_OPTIONAL_SETTER(nr,         set_nr,                int)
MOOTATION_OPTIONAL_SETTER(kappa,      set_kappa,             double)
MOOTATION_OPTIONAL_SETTER(K,          set_K,                 int)
MOOTATION_OPTIONAL_SETTER(n_clusters, set_n_clusters,        int)
MOOTATION_OPTIONAL_SETTER(theta,      set_theta,             double)
MOOTATION_OPTIONAL_SETTER(alpha,      set_alpha,             double)
MOOTATION_OPTIONAL_SETTER(F,          set_F,                 double)
MOOTATION_OPTIONAL_SETTER(CR,         set_CR,                double)
MOOTATION_OPTIONAL_SETTER(div,        set_div,               int)

#undef MOOTATION_OPTIONAL_SETTER

// ── Run configuration ───────────────────────────────────────────────────────
// NOT named PyConfig: CPython's own Python.h defines that (PEP 587).
// Every knob is optional. `has_*` is false until the caller assigns, so an
// unset knob leaves the algorithm's paper default alone.
struct RunConfig {
    int      pop_size = 100;
    int      n_gen    = 250;
    unsigned seed     = 0;
    mootation::ConstraintMode constraint_mode = mootation::ConstraintMode::NONE;

    std::optional<double> eta_c, eta_m, pc, pm, delta, kappa, theta, alpha, F, CR;
    std::optional<int>    T, nr, K, n_clusters, div;

    // Warm start. Empty means a fresh random population. Vars and objs are
    // what every algorithm shares — which is what lets a population saved by
    // NSGA-II seed a MOEA/D run. A constrained run also needs the individual
    // constraint values (the algorithms compare those, not the aggregate cv):
    // minimize() recomputes them from `constraints`, and the binding refuses
    // a constrained warm start without them rather than planting a population
    // every one of whose constraints reads as satisfied.
    std::vector<std::vector<double>> seed_variables;
    std::vector<std::vector<double>> seed_objectives;
    std::vector<std::vector<double>> seed_limits;

    // Per-generation observer. When set and record_every > 0, the run is
    // stepped one generation at a time and on_generation(gen, objectives) is
    // called after setup (gen = 0) and after every record_every-th generation
    // (and the last one). `objectives` are the current answer set's rows —
    // the same view the final Result returns — so a caller can record IGD or
    // hypervolume against the evaluation count it keeps in its own evaluator.
    // Off by default: optimize() runs uninterrupted.
    std::function<void(int, std::vector<std::vector<double>>)> on_generation;
    int record_every = 0;

    // Evaluation budget. 0 = run n_gen steps. > 0 = step until this many
    // evaluations have been spent; n_gen is then ignored. A step is not a
    // generation of pop_size evaluations for every core: NIMMO evaluates one
    // offspring per step and MOEA/D-DRA and -AWA a fifth of the population,
    // so a budget in steps is not a budget. The check sits between steps, so
    // a generational core overshoots by less than one generation. The
    // observer then fires every record_every * pop_size evaluations instead
    // of every record_every steps, which keeps trajectories comparable.
    long long max_evaluations = 0;
};

struct PyResult {
    std::vector<std::vector<double>> objectives;
    std::vector<std::vector<double>> variables;
    std::vector<double>              cv;
    std::size_t                      active_n = 0;
    // Knobs the caller set that this algorithm does not have. Reported rather
    // than dropped: a run configured with an ignored parameter is not the run
    // the caller asked for.
    std::vector<std::string>         ignored;
    // Evaluations the run spent, setup included.
    long long                        evaluations = 0;
};

template <typename Tag, typename Core>
PyResult run_core(const RunConfig& cfg)
{
    using namespace mootation;

    Problem<Tag> prob;
    prob.bounds.reserve(g_problem->bounds.size());
    for (auto& b : g_problem->bounds)
        prob.bounds.emplace_back(std::optional<double>(b.first),
                                 std::optional<double>(b.second));

    DataVault<Tag>      vault(cfg.pop_size, prob);
    if (g_problem->evaluate_batch) vault.set_batch_executor(&py_run_batch);
    Optimizer<Tag, Core> opt(std::move(vault), defer_setup);

    auto&                    alg = opt.get_algorithm();
    std::vector<std::string> ignored;
    auto note = [&](bool applied, const char* name) {
        if (!applied) ignored.emplace_back(name);
    };

    alg.set_seed(cfg.seed);
    alg.constraint_mode = cfg.constraint_mode;

    // t_max is not a user knob but a schedule input: several algorithms anneal
    // against it, and a default of 1000 against a 250-generation run is not the
    // paper's schedule. Always pass the real budget where the core takes it.
    // Under an evaluation budget the number of steps is not known yet: start
    // from budget / pop_size and correct it after the first step (below).
    const bool by_evaluations = cfg.max_evaluations > 0;
    if (by_evaluations)
        apply_t_max(alg, static_cast<int>(std::min<long long>(
            INT_MAX, (cfg.max_evaluations + cfg.pop_size - 1) / std::max(1, cfg.pop_size))));
    else
        apply_t_max(alg, cfg.n_gen);

    if (cfg.eta_c)      note(apply_eta_c(alg, *cfg.eta_c),           "eta_c");
    if (cfg.eta_m)      note(apply_eta_m(alg, *cfg.eta_m),           "eta_m");
    if (cfg.pc)         note(apply_pc(alg, *cfg.pc),                 "pc");
    if (cfg.pm)         note(apply_pm(alg, *cfg.pm),                 "pm");
    if (cfg.T)          note(apply_T(alg, *cfg.T),                   "T");
    if (cfg.delta)      note(apply_delta(alg, *cfg.delta),           "delta");
    if (cfg.nr)         note(apply_nr(alg, *cfg.nr),                 "nr");
    if (cfg.kappa)      note(apply_kappa(alg, *cfg.kappa),           "kappa");
    if (cfg.K)          note(apply_K(alg, *cfg.K),                   "K");
    if (cfg.n_clusters) note(apply_n_clusters(alg, *cfg.n_clusters), "n_clusters");
    if (cfg.theta)      note(apply_theta(alg, *cfg.theta),           "theta");
    if (cfg.alpha)      note(apply_alpha(alg, *cfg.alpha),           "alpha");
    if (cfg.F)          note(apply_F(alg, *cfg.F),                   "F");
    if (cfg.CR)         note(apply_CR(alg, *cfg.CR),                 "CR");
    if (cfg.div)        note(apply_div(alg, *cfg.div),               "div");

    {
        py::gil_scoped_release unlock;   // the callback re-acquires per batch
        if (!cfg.seed_variables.empty()) {
            // setup_with_seed plants the population WITHOUT evaluating it: the
            // objectives come from the file, so a warm start costs zero
            // function evaluations. That is the whole point when an evaluation
            // is a solver run.
            if (g_problem->n_limits > 0 && cfg.seed_limits.empty())
                throw std::invalid_argument(
                    "mootation: this run has " + std::to_string(g_problem->n_limits) +
                    " constraints but the seed population carries no per-constraint "
                    "values; pass seed_limits (minimize() recomputes them from "
                    "`constraints`)");
            opt.setup_with_seed(cfg.seed_variables, cfg.seed_objectives, {},
                                cfg.seed_limits);
        } else {
            opt.setup();
        }
        const bool observe = cfg.on_generation && cfg.record_every > 0;
        auto emit = [&](int g) {
            auto& v = opt.get_vault();
            std::size_t n = std::min<std::size_t>(
                v.active_n(), static_cast<std::size_t>(v.pop_size()));
            std::vector<std::vector<double>> P;
            P.reserve(n);
            for (std::size_t i = 0; i < n; ++i) P.push_back(v.objectives_of(i));
            py::gil_scoped_acquire gil;
            cfg.on_generation(g, std::move(P));
        };
        if (!by_evaluations) {
            if (observe) {
                emit(0);
                for (int g = 1; g <= cfg.n_gen; ++g) {
                    opt.step();
                    if (g % cfg.record_every == 0 || g == cfg.n_gen) emit(g);
                }
            } else {
                opt.optimize(cfg.n_gen);
            }
        } else {
            if (observe) emit(0);
            const long long start  = g_evaluations.load();
            const long long stride = static_cast<long long>(cfg.record_every) *
                                     std::max(1, cfg.pop_size);
            long long next_record  = start + stride;
            long long idle         = 0;   // consecutive steps that evaluated nothing
            for (int g = 1; g_evaluations.load() < cfg.max_evaluations; ++g) {
                const long long before = g_evaluations.load();
                opt.step();
                const long long now = g_evaluations.load();
                if (now > before) {
                    idle = 0;
                } else if (++idle >= 10000) {
                    throw std::runtime_error(
                        "mootation: 10000 steps in a row evaluated nothing; this core "
                        "cannot run on an evaluation budget, use n_gen");
                }
                if (g == 1) {
                    // The real cost of a step is known now: give the schedule the
                    // number of steps the budget buys (MOEA/D-AWA anneals over
                    // five times more steps than a generational core).
                    const long long per  = std::max(1LL, now - start);
                    const long long left = std::max(0LL, cfg.max_evaluations - now);
                    apply_t_max(alg, static_cast<int>(std::min<long long>(
                        INT_MAX, 1 + (left + per - 1) / per)));
                }
                const bool last = now >= cfg.max_evaluations;
                if (observe && (now >= next_record || last)) {
                    emit(g);
                    while (next_record <= now) next_record += stride;
                }
            }
        }
    }

    auto&    v = opt.get_vault();
    PyResult r;
    // NOT active_n(): steady-state cores (moead_de, moead_dd, hlmea, adaw,
    // ...) park a persistent scratch slot at active index pop_size(), so
    // active_n() is pop_size() + 1 for them. Returning that extra slot hands
    // the caller an unselected offspring dressed as a member of the answer
    // set — enough to skew any IGD or hypervolume computed from it, and
    // invisible unless you count the rows. See data_vault.hpp, "SCRATCH SLOTS
    // AND CONSUMERS".
    r.active_n = std::min<std::size_t>(v.active_n(),
                                       static_cast<std::size_t>(v.pop_size()));
    r.ignored  = std::move(ignored);
    r.evaluations = g_evaluations.load();
    r.objectives.reserve(r.active_n);
    r.variables.reserve(r.active_n);
    for (std::size_t i = 0; i < r.active_n; ++i) {
        r.objectives.push_back(v.objectives_of(i));
        r.variables.push_back(v.variables_of(i));
        r.cv.push_back(v.get_cv(i));
    }
    return r;
}

// ── Dispatch, generated from include/mootation/algorithms.def ───────────────────────────
PyResult run(const std::string& name, PyProblem& problem, const RunConfig& cfg)
{
    if (problem.bounds.empty())
        throw std::invalid_argument("problem.bounds is empty");

    g_problem = &problem;
    g_evaluations = 0;
    struct Guard { ~Guard() { g_problem = nullptr; } } guard;

#define MOOTATION_ALG(KEY, IND, CORE) \
    if (name == #KEY) return run_core<PyTag_##KEY, mootation::CORE<PyTag_##KEY>>(cfg);
#include "mootation/algorithms.def"
#undef MOOTATION_ALG

    throw std::invalid_argument("unknown algorithm: " + name);
}

std::vector<std::string> algorithm_names()
{
    std::vector<std::string> v;
#define MOOTATION_ALG(KEY, IND, CORE) v.emplace_back(#KEY);
#include "mootation/algorithms.def"
#undef MOOTATION_ALG
    return v;
}

} // namespace

PYBIND11_MODULE(_core, m)
{
    m.doc() = "MOOtation — multi- and many-objective evolutionary algorithms";
    m.attr("__version__") = mootation::version();
    // The git revision this binary was built from (python/git_stamp.cmake);
    // "unknown" when built outside a git checkout or by another build system.
    m.attr("__git_commit__") = MOOTATION_GIT_COMMIT;
    m.attr("__git_dirty__")  = static_cast<bool>(MOOTATION_GIT_DIRTY);

    py::enum_<mootation::ConstraintMode>(m, "ConstraintMode")
        .value("NONE",           mootation::ConstraintMode::NONE)
        .value("FEASIBILITY",    mootation::ConstraintMode::FEASIBILITY)
        .value("EPS_CONSTRAINT", mootation::ConstraintMode::EPS_CONSTRAINT)
        .value("CDP",            mootation::ConstraintMode::CDP);

    py::class_<PyProblem>(m, "Problem")
        .def(py::init<>())
        .def_readwrite("bounds",         &PyProblem::bounds)
        .def_readwrite("n_objectives",   &PyProblem::n_objectives)
        .def_readwrite("n_limits",       &PyProblem::n_limits)
        .def_readwrite("evaluate",       &PyProblem::evaluate)
        .def_readwrite("evaluate_batch", &PyProblem::evaluate_batch)
        .def_readwrite("limits_batch",   &PyProblem::limits_batch);

    py::class_<RunConfig>(m, "Config")
        .def(py::init<>())
        .def_readwrite("pop_size",        &RunConfig::pop_size)
        .def_readwrite("n_gen",           &RunConfig::n_gen)
        .def_readwrite("seed",            &RunConfig::seed)
        .def_readwrite("constraint_mode", &RunConfig::constraint_mode)
        .def_readwrite("eta_c",           &RunConfig::eta_c)
        .def_readwrite("eta_m",           &RunConfig::eta_m)
        .def_readwrite("pc",              &RunConfig::pc)
        .def_readwrite("pm",              &RunConfig::pm)
        .def_readwrite("T",               &RunConfig::T)
        .def_readwrite("delta",           &RunConfig::delta)
        .def_readwrite("nr",              &RunConfig::nr)
        .def_readwrite("kappa",           &RunConfig::kappa)
        .def_readwrite("K",               &RunConfig::K)
        .def_readwrite("n_clusters",      &RunConfig::n_clusters)
        .def_readwrite("theta",           &RunConfig::theta)
        .def_readwrite("alpha",           &RunConfig::alpha)
        .def_readwrite("F",               &RunConfig::F)
        .def_readwrite("CR",              &RunConfig::CR)
        .def_readwrite("div",             &RunConfig::div)
        .def_readwrite("seed_variables",  &RunConfig::seed_variables)
        .def_readwrite("seed_objectives", &RunConfig::seed_objectives)
        .def_readwrite("seed_limits",     &RunConfig::seed_limits)
        .def_readwrite("on_generation",   &RunConfig::on_generation,
                       "Observer called as on_generation(gen, objectives) every "
                       "record_every generations (gen 0 = after setup).")
        .def_readwrite("record_every",    &RunConfig::record_every,
                       "0 = no observer; k > 0 = call on_generation every k generations "
                       "(every k * pop_size evaluations under max_evaluations).")
        .def_readwrite("max_evaluations", &RunConfig::max_evaluations,
                       "0 = run n_gen steps; > 0 = step until this many evaluations are "
                       "spent (n_gen is then ignored).");

    py::class_<PyResult>(m, "Result")
        .def_readonly("objectives", &PyResult::objectives)
        .def_readonly("variables",  &PyResult::variables)
        .def_readonly("cv",         &PyResult::cv)
        .def_readonly("active_n",   &PyResult::active_n)
        .def_readonly("ignored",    &PyResult::ignored,
                      "Knobs you set that this algorithm does not have.")
        .def_readonly("evaluations", &PyResult::evaluations,
                      "Evaluations the run spent, setup included.");

    m.def("algorithms", &algorithm_names,
          "Names accepted by run(), straight from include/mootation/algorithms.def.");
    m.def("run", &run, py::arg("name"), py::arg("problem"), py::arg("config"),
          "Run one algorithm and return its final population.");
}
