// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// pybind11 module `mootation`.
//
// The algorithm table is NOT written out here. It is generated from
// include/mootation/algorithms.def — the same X-macro the test suite iterates over — so a
// new algorithm becomes callable from Python by adding the one line it already
// needs, and the binding cannot silently fall behind the library. CI fails if a
// header is missing from that file.
//
// Every core exposes set_seed/setup/step, but the tuning knobs differ per
// algorithm: only 19 of the 58 have set_t_max, 10 have set_T, 6 have set_kappa.
// Rather than a per-algorithm dispatch, each optional setter is detected with
// SFINAE and applied only where it exists. A knob the caller sets that the
// chosen algorithm does not have is REPORTED, not ignored — silently dropping
// it is how a run ends up not being the run you configured.
//
// Objectives are evaluated by a Python callback. That crosses the GIL once per
// batch, so use `evaluate_batch` for anything non-trivial.
// ============================================================================

#include <algorithm>
#include <atomic>
#include <climits>
#include <cmath>
#include <map>
#include <unordered_map>
#include <memory>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>

#include <pybind11/functional.h>
#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>
#include <pybind11/stl.h>

#include <mootation/hypervolume.hpp>
#include <mootation/mootation.hpp>

// Generated by python/git_stamp.cmake on every build; absent when the module is
// built some other way, and then the revision is simply "unknown".
#if __has_include("mootation_git_stamp.h")
#include "mootation_git_stamp.h"
#endif
#ifndef MOOTATION_GIT_COMMIT
#define MOOTATION_GIT_COMMIT "unknown"
#endif
#ifndef MOOTATION_GIT_DIRTY
#define MOOTATION_GIT_DIRTY 0
#endif

namespace py = pybind11;

namespace {

// ── The problem, as configured from Python ─────────────────────────────────
struct PyProblem {
    std::vector<std::pair<double, double>> bounds;
    int    n_objectives = 2;
    int    n_limits     = 0;
    // One of the two. evaluate_batch is preferred: it crosses the GIL once per
    // generation instead of once per individual.
    std::function<std::vector<double>(std::vector<double>)>               evaluate;
    std::function<std::vector<std::vector<double>>(
        std::vector<std::vector<double>>)>                                evaluate_batch;
    // Optional; must return one row of limits per individual, same convention
    // as the C++ side: <= 0 satisfied, > 0 is the violation.
    std::function<std::vector<std::vector<double>>(
        std::vector<std::vector<double>>)>                                limits_batch;
};

// The active problem for the current run. A raw pointer is enough because a run
// is single-threaded from Python's side and the pointer outlives the vault.
PyProblem* g_problem = nullptr;

// Evaluations spent by the current run, counted where the Python evaluator is
// actually called: one per individual through eval_into, the batch size through
// py_run_batch. A warm start plants objectives without evaluating and costs
// nothing. Atomic because the step loop reads it with the GIL released.
std::atomic<long long> g_evaluations{0};

// ── Operator statistics (the 2026-09-23 task, A2/B4/D2) ─────────────────────
// Asked for with RunConfig::operator_stats; nothing below runs otherwise, and
// nothing below draws a random number or evaluates anything, so a run's
// result is the same with or without it (tests/compat_dump.cpp, and
// test_run_layer's operator-statistics test compares the two).
//
// Per step: the population before it (the "parents"), every point the step
// evaluated (the "offspring") and the population after it. The library does
// not track which individuals an offspring came from across its 58 cores, so
// the relations are to the parent POPULATION:
//   survival    an offspring is in the next population. By value: the next
//               population holds more copies of its variable vector than the
//               parents did (a clone of a surviving parent is not counted, a
//               child copied into several MOEA/D neighbours counts once);
//   nd          no parent dominates the offspring (objectives only);
//   step        distance to the nearest parent in variables, over the box
//               diagonal ||ub - lb||.
// The out-of-box counts come from the repair sites (operators/bound_repair.hpp).
struct OpStats {
    bool on = false;
    std::vector<std::vector<double>> log_x, log_f;           // this step's evaluations
    std::vector<std::vector<double>> par_x, par_f;           // the population before it
    // running sums: since the last operator_stats() read, and for the run
    long long off = 0, surv = 0, nd = 0, step_n = 0;
    double    step = 0.0;
    long long t_off = 0, t_surv = 0, t_nd = 0, t_step_n = 0;
    double    t_step = 0.0;
    long long evals_read = 0;
    long long setup_evals = 0;                                // not offspring
    mootation::ops::RepairCounts rc_read;
};
OpStats g_ops;

inline std::string vec_key(const std::vector<double>& x)
{
    return std::string(reinterpret_cast<const char*>(x.data()), x.size() * sizeof(double));
}

template <typename Vault>
void ops_before_step(Vault& v)
{
    g_ops.log_x.clear();
    g_ops.log_f.clear();
    g_ops.par_x.clear();
    g_ops.par_f.clear();
    const std::size_t n = std::min<std::size_t>(v.active_n(), static_cast<std::size_t>(v.pop_size()));
    for (std::size_t i = 0; i < n; ++i) {
        if (v.is_dirty(i)) continue;              // never evaluate on the observer's behalf
        g_ops.par_x.push_back(v.variables_of(i));
        g_ops.par_f.push_back(v.objectives_of(i));
    }
}

template <typename Vault>
void ops_after_step(Vault& v)
{
    const auto& O = g_ops.log_x;
    if (O.empty()) return;
    // survival, by multiset count of exact variable vectors
    std::unordered_map<std::string, long long> cp, cq, co;
    for (const auto& x : g_ops.par_x) ++cp[vec_key(x)];
    for (const auto& x : O) ++co[vec_key(x)];
    const std::size_t n = std::min<std::size_t>(v.active_n(), static_cast<std::size_t>(v.pop_size()));
    for (std::size_t i = 0; i < n; ++i) {
        auto k = vec_key(v.variables_of(i));
        if (co.count(k)) ++cq[k];
    }
    long long surv = 0;
    for (const auto& kv : co) {
        auto q = cq.find(kv.first);
        auto pp = cp.find(kv.first);
        long long extra = (q == cq.end() ? 0 : q->second) - (pp == cp.end() ? 0 : pp->second);
        surv += std::min(kv.second, std::max(0LL, extra));
    }
    // nondominated by the parents, and the step to the nearest parent
    double diag = 0.0;
    for (const auto& b : g_problem->bounds) diag += (b.second - b.first) * (b.second - b.first);
    diag = std::sqrt(diag);
    long long nd = 0, step_n = 0;
    double step = 0.0;
    for (std::size_t c = 0; c < O.size(); ++c) {
        const auto& f = g_ops.log_f[c];
        bool dominated = false;
        for (const auto& pf : g_ops.par_f) {
            bool le = true, lt = false;
            for (std::size_t j = 0; j < f.size() && le; ++j) {
                le = pf[j] <= f[j];
                lt = lt || pf[j] < f[j];
            }
            if (le && lt) { dominated = true; break; }
        }
        nd += dominated ? 0 : 1;
        if (!g_ops.par_x.empty() && diag > 0.0) {
            double best = 1e300;
            for (const auto& px : g_ops.par_x) {
                double d2 = 0.0;
                for (std::size_t j = 0; j < px.size(); ++j) d2 += (O[c][j] - px[j]) * (O[c][j] - px[j]);
                best = std::min(best, d2);
            }
            step += std::sqrt(best) / diag;
            ++step_n;
        }
    }
    const long long off = static_cast<long long>(O.size());
    g_ops.off += off;   g_ops.surv += surv;   g_ops.nd += nd;
    g_ops.step += step; g_ops.step_n += step_n;
    g_ops.t_off += off; g_ops.t_surv += surv; g_ops.t_nd += nd;
    g_ops.t_step += step; g_ops.t_step_n += step_n;
}

inline void ops_log(const std::vector<double>& x, const std::vector<double>& f)
{
    if (!g_ops.on) return;
    g_ops.log_x.push_back(x);
    g_ops.log_f.push_back(f);
}

// Objective/limit evaluation, shared by every generated Problem<> below.
inline void eval_into(const std::vector<double>& vars,
                      std::vector<double>&       objs,
                      std::vector<double>&       lims)
{
    if (!g_problem) throw std::runtime_error("mootation: no active problem");
    py::gil_scoped_acquire gil;

    if (g_problem->evaluate_batch) {
        auto out = g_problem->evaluate_batch({vars});
        if (out.empty()) throw std::runtime_error("evaluate_batch returned nothing");
        objs = out.front();
    } else if (g_problem->evaluate) {
        objs = g_problem->evaluate(vars);
    } else {
        throw std::runtime_error("set problem.evaluate or problem.evaluate_batch");
    }
    ++g_evaluations;
    if (static_cast<int>(objs.size()) != g_problem->n_objectives)
        throw std::runtime_error("the evaluator returned the wrong number of objectives");
    ops_log(vars, objs);

    if (g_problem->n_limits > 0) {
        if (!g_problem->limits_batch)
            throw std::runtime_error("n_limits > 0 requires problem.limits_batch");
        auto lim = g_problem->limits_batch({vars});
        if (lim.empty()) throw std::runtime_error("limits_batch returned nothing");
        lims = lim.front();
        if (static_cast<int>(lims.size()) != g_problem->n_limits)
            throw std::runtime_error("limits_batch returned the wrong width");
    }
}

// The BatchExecutor installed when the caller supplied evaluate_batch: the
// whole dirty set crosses the GIL in ONE call, which is what "batched
// evaluation" promises. Without it DataVault falls back to calc_objs one
// individual at a time and a batch function only ever sees single rows.
void py_run_batch(const mootation::BatchRequest& req, mootation::BatchResponse& resp)
{
    if (!g_problem) throw std::runtime_error("mootation: no active problem");
    py::gil_scoped_acquire gil;

    auto out = g_problem->evaluate_batch(req.variables);
    if (out.size() != req.size())
        throw std::runtime_error(
            "evaluate_batch returned " + std::to_string(out.size()) +
            " rows for a batch of " + std::to_string(req.size()));
    for (const auto& row : out)
        if (static_cast<int>(row.size()) != g_problem->n_objectives)
            throw std::runtime_error("the evaluator returned the wrong number of objectives");
    g_evaluations += static_cast<long long>(req.size());
    for (std::size_t i = 0; i < req.size(); ++i) ops_log(req.variables[i], out[i]);
    resp.objectives = std::move(out);

    if (g_problem->n_limits > 0) {
        if (!g_problem->limits_batch)
            throw std::runtime_error("n_limits > 0 requires problem.limits_batch");
        auto lim = g_problem->limits_batch(req.variables);
        if (lim.size() != req.size())
            throw std::runtime_error(
                "limits_batch returned " + std::to_string(lim.size()) +
                " rows for a batch of " + std::to_string(req.size()));
        for (const auto& row : lim)
            if (static_cast<int>(row.size()) != g_problem->n_limits)
                throw std::runtime_error("limits_batch returned the wrong width");
        resp.limits = std::move(lim);
    } else {
        resp.limits.clear();
    }
}

} // namespace

// Each algorithm needs ITS OWN individual type — crEA reads .cluster/.rank,
// NSGA-II reads .rank/.crowding_distance — so one tag per algorithm is
// generated from the same X-macro that drives the dispatch. The Problem<>
// specialization has to be written out in full: Based_Individual befriends
// Problem<T> only, so nothing else may touch ind.variables/objectives/limits.
#define MOOTATION_PY_PROBLEM(TAG, BASE)                                        \
    namespace { struct TAG : public mootation::BASE {}; }                      \
    namespace mootation {                                                      \
    template <>                                                                \
    class Problem<TAG> {                                                       \
    public:                                                                    \
        std::vector<std::pair<std::optional<double>, std::optional<double>>>   \
            bounds;                                                            \
        int get_vars_n() const { return static_cast<int>(bounds.size()); }     \
        int get_bin_vars_n() const { return 0; }                               \
        int get_objs_n() const                                                 \
        {                                                                      \
            return g_problem ? g_problem->n_objectives : 0;                    \
        }                                                                      \
        int get_lims_n() const                                                 \
        {                                                                      \
            return g_problem ? g_problem->n_limits : 0;                        \
        }                                                                      \
        void calc_objs(TAG& ind) const                                         \
        {                                                                      \
            eval_into(ind.variables, ind.objectives, ind.limits);              \
        }                                                                      \
    };                                                                         \
    }

#define MOOTATION_ALG(KEY, IND, CORE) MOOTATION_PY_PROBLEM(PyTag_##KEY, IND)
#include "mootation/algorithms.def"
#undef MOOTATION_ALG

namespace {

// ── Optional-setter detection ───────────────────────────────────────────────
// One macro per knob: a trait that asks "does this core have set_X(T)?", and an
// apply() that calls it when it does and reports when it does not.
#define MOOTATION_OPTIONAL_SETTER(NAME, SETTER, TYPE)                          \
    template <typename C, typename = void>                                     \
    struct has_##NAME : std::false_type {};                                    \
    template <typename C>                                                      \
    struct has_##NAME<C, std::void_t<decltype(std::declval<C&>().SETTER(       \
                             std::declval<TYPE>()))>> : std::true_type {};     \
    template <typename C>                                                      \
    bool apply_##NAME(C& core, TYPE v)                                         \
    {                                                                          \
        if constexpr (has_##NAME<C>::value) { core.SETTER(v); return true; }    \
        else { (void)core; (void)v; return false; }                            \
    }

MOOTATION_OPTIONAL_SETTER(t_max,      set_t_max,             int)
MOOTATION_OPTIONAL_SETTER(eta_c,      set_eta_crossover,     double)
MOOTATION_OPTIONAL_SETTER(eta_m,      set_eta_mutation,      double)
MOOTATION_OPTIONAL_SETTER(pc,         set_pc,                double)
MOOTATION_OPTIONAL_SETTER(pm,         set_pm,                double)
MOOTATION_OPTIONAL_SETTER(T,          set_T,                 int)
MOOTATION_OPTIONAL_SETTER(delta,      set_delta,             double)
MOOTATION_OPTIONAL_SETTER(nr,         set_nr,                int)
MOOTATION_OPTIONAL_SETTER(kappa,      set_kappa,             double)
MOOTATION_OPTIONAL_SETTER(K,          set_K,                 int)
MOOTATION_OPTIONAL_SETTER(n_clusters, set_n_clusters,        int)
MOOTATION_OPTIONAL_SETTER(theta,      set_theta,             double)
MOOTATION_OPTIONAL_SETTER(alpha,      set_alpha,             double)
MOOTATION_OPTIONAL_SETTER(F,          set_F,                 double)
MOOTATION_OPTIONAL_SETTER(CR,         set_CR,                double)
MOOTATION_OPTIONAL_SETTER(div,        set_div,               int)
MOOTATION_OPTIONAL_SETTER(normalize,  set_normalize,         bool)
MOOTATION_OPTIONAL_SETTER(bound_repair, set_bound_repair,    mootation::ops::BoundRepair)
MOOTATION_OPTIONAL_SETTER(crossover,  set_crossover,         mootation::ops::Crossover)
MOOTATION_OPTIONAL_SETTER(mutation,   set_mutation,          mootation::ops::Mutation)
MOOTATION_OPTIONAL_SETTER(mutation_scale, set_mutation_scale, double)
MOOTATION_OPTIONAL_SETTER(mixture_q,  set_mixture_q,         double)
MOOTATION_OPTIONAL_SETTER(blx_alpha,  set_blx_alpha,         double)

#undef MOOTATION_OPTIONAL_SETTER

// ── Run configuration ───────────────────────────────────────────────────────
// NOT named PyConfig: CPython's own Python.h defines that (PEP 587).
// Every knob is optional. `has_*` is false until the caller assigns, so an
// unset knob leaves the algorithm's paper default alone.
struct RunConfig {
    int      pop_size = 100;
    int      n_gen    = 250;
    unsigned seed     = 0;
    mootation::ConstraintMode constraint_mode = mootation::ConstraintMode::NONE;

    std::optional<double> eta_c, eta_m, pc, pm, delta, kappa, theta, alpha, F, CR;
    std::optional<int>    T, nr, K, n_clusters, div;
    // The objective normalization that ibea_eplus, r2ibea, two_arch2 and
    // moead_am2m can switch; each header says which setting is the paper's.
    std::optional<bool>   normalize;
    // What an operator that can leave the box does there (text_knobs() in
    // settings.hpp); the algorithms without such an operator report it ignored.
    std::optional<std::string> bound_repair;
    // Switchable operators (nsga2, ibea_eplus, spea2_sde, agemoea; moead_de the
    // mutation only) and their parameters: text_knobs() / knob_names().
    std::optional<std::string> crossover, mutation;
    std::optional<double>      mutation_scale, mixture_q, blx_alpha;
    // The SBX operator's share of crossed variables (ops::sbx_var_prob, 0.5),
    // for this run only.
    std::optional<double>      sbx_var_prob;

    // Warm start. Empty means a fresh random population. Vars and objs are
    // what every algorithm shares — which is what lets a population saved by
    // NSGA-II seed a MOEA/D run. A constrained run also needs the individual
    // constraint values (the algorithms compare those, not the aggregate cv):
    // minimize() recomputes them from `constraints`, and the binding refuses
    // a constrained warm start without them rather than planting a population
    // every one of whose constraints reads as satisfied.
    std::vector<std::vector<double>> seed_variables;
    std::vector<std::vector<double>> seed_objectives;
    std::vector<std::vector<double>> seed_limits;

    // Per-generation observer. When set and record_every > 0, the run is
    // stepped one generation at a time and on_generation(gen, objectives) is
    // called after setup (gen = 0) and after every record_every-th generation
    // (and the last one). `objectives` are the current answer set's rows —
    // the same view the final Result returns — so a caller can record IGD or
    // hypervolume against the evaluation count it keeps in its own evaluator.
    // Off by default: optimize() runs uninterrupted.
    std::function<void(int, std::vector<std::vector<double>>)> on_generation;
    int record_every = 0;

    // Evaluation budget. 0 = run n_gen steps. > 0 = step until this many
    // evaluations have been spent; n_gen is then ignored. A step is not a
    // generation of pop_size evaluations for every core: NIMMO evaluates one
    // offspring per step and MOEA/D-DRA and -AWA a fifth of the population,
    // so a budget in steps is not a budget. The check sits between steps, so
    // a generational core overshoots by less than one generation. The
    // observer then fires every record_every * pop_size evaluations instead
    // of every record_every steps, which keeps trajectories comparable.
    long long max_evaluations = 0;
    // Operator statistics along the run (the per-step bookkeeping above); read
    // them with operator_stats() from the on_generation observer.
    bool operator_stats = false;
};

struct PyResult {
    std::vector<std::vector<double>> objectives;
    std::vector<std::vector<double>> variables;
    std::vector<double>              cv;
    std::size_t                      active_n = 0;
    // Knobs the caller set that this algorithm does not have. Reported rather
    // than dropped: a run configured with an ignored parameter is not the run
    // the caller asked for.
    std::vector<std::string>         ignored;
    // Evaluations the run spent, setup included.
    long long                        evaluations = 0;
    // Every variation operator the run used, with its bound repair ("none" for
    // one that cannot leave the box), in order of first use.
    std::vector<std::pair<std::string, std::string>> operators;
    // The run's operator statistics (operator_stats() over the whole run);
    // empty unless RunConfig::operator_stats.
    std::map<std::string, double>    operator_totals;
};

template <typename Tag, typename Core>
PyResult run_core(const RunConfig& cfg)
{
    using namespace mootation;

    Problem<Tag> prob;
    prob.bounds.reserve(g_problem->bounds.size());
    for (auto& b : g_problem->bounds)
        prob.bounds.emplace_back(std::optional<double>(b.first),
                                 std::optional<double>(b.second));

    DataVault<Tag>      vault(cfg.pop_size, prob);
    if (g_problem->evaluate_batch) vault.set_batch_executor(&py_run_batch);
    Optimizer<Tag, Core> opt(std::move(vault), defer_setup);

    auto&                    alg = opt.get_algorithm();
    std::vector<std::string> ignored;
    auto note = [&](bool applied, const char* name) {
        if (!applied) ignored.emplace_back(name);
    };

    alg.set_seed(cfg.seed);
    alg.constraint_mode = cfg.constraint_mode;

    // t_max is not a user knob but a schedule input: several algorithms anneal
    // against it, and a default of 1000 against a 250-generation run is not the
    // paper's schedule. Always pass the real budget where the core takes it.
    // Under an evaluation budget the number of steps is not known yet: start
    // from budget / pop_size and correct it after the first step (below).
    const bool by_evaluations = cfg.max_evaluations > 0;
    if (by_evaluations)
        apply_t_max(alg, static_cast<int>(std::min<long long>(
            INT_MAX, (cfg.max_evaluations + cfg.pop_size - 1) / std::max(1, cfg.pop_size))));
    else
        apply_t_max(alg, cfg.n_gen);

    if (cfg.eta_c)      note(apply_eta_c(alg, *cfg.eta_c),           "eta_c");
    if (cfg.eta_m)      note(apply_eta_m(alg, *cfg.eta_m),           "eta_m");
    if (cfg.pc)         note(apply_pc(alg, *cfg.pc),                 "pc");
    if (cfg.pm)         note(apply_pm(alg, *cfg.pm),                 "pm");
    if (cfg.T)          note(apply_T(alg, *cfg.T),                   "T");
    if (cfg.delta)      note(apply_delta(alg, *cfg.delta),           "delta");
    if (cfg.nr)         note(apply_nr(alg, *cfg.nr),                 "nr");
    if (cfg.kappa)      note(apply_kappa(alg, *cfg.kappa),           "kappa");
    if (cfg.K)          note(apply_K(alg, *cfg.K),                   "K");
    if (cfg.n_clusters) note(apply_n_clusters(alg, *cfg.n_clusters), "n_clusters");
    if (cfg.theta)      note(apply_theta(alg, *cfg.theta),           "theta");
    if (cfg.alpha)      note(apply_alpha(alg, *cfg.alpha),           "alpha");
    if (cfg.F)          note(apply_F(alg, *cfg.F),                   "F");
    if (cfg.CR)         note(apply_CR(alg, *cfg.CR),                 "CR");
    if (cfg.div)        note(apply_div(alg, *cfg.div),               "div");
    if (cfg.normalize)  note(apply_normalize(alg, *cfg.normalize),   "normalize");
    if (cfg.bound_repair) {
        auto how = ops::parse_bound_repair(*cfg.bound_repair);
        if (!how)
            throw std::invalid_argument(
                "bound_repair = '" + *cfg.bound_repair + "': one of clip, reflect, random, "
                "midpoint, resample, wrap, native");
        note(apply_bound_repair(alg, *how), "bound_repair");
    }
    if (cfg.crossover) {
        auto c = ops::parse_crossover(*cfg.crossover);
        if (!c)
            throw std::invalid_argument("crossover = '" + *cfg.crossover +
                                        "': one of sbx, uniform, blx_alpha");
        note(apply_crossover(alg, *c), "crossover");
    }
    if (cfg.mutation) {
        auto m = ops::parse_mutation(*cfg.mutation);
        if (!m)
            throw std::invalid_argument("mutation = '" + *cfg.mutation + "': one of polynomial, "
                                        "gaussian, cauchy, uniform_reset, mixture, mixture_cauchy");
        note(apply_mutation(alg, *m), "mutation");
    }
    if (cfg.mutation_scale) note(apply_mutation_scale(alg, *cfg.mutation_scale), "mutation_scale");
    if (cfg.mixture_q)      note(apply_mixture_q(alg, *cfg.mixture_q),           "mixture_q");
    if (cfg.blx_alpha)      note(apply_blx_alpha(alg, *cfg.blx_alpha),           "blx_alpha");
    std::optional<ops::ScopedSbxVarProb> var_prob;
    if (cfg.sbx_var_prob) {
        if (!(*cfg.sbx_var_prob >= 0.0 && *cfg.sbx_var_prob <= 1.0))
            throw std::invalid_argument("sbx_var_prob must be in [0, 1]");
        var_prob.emplace(*cfg.sbx_var_prob);
    }

    {
        py::gil_scoped_release unlock;   // the callback re-acquires per batch
        if (!cfg.seed_variables.empty()) {
            // setup_with_seed plants the population WITHOUT evaluating it: the
            // objectives come from the file, so a warm start costs zero
            // function evaluations. That is the whole point when an evaluation
            // is a solver run.
            if (g_problem->n_limits > 0 && cfg.seed_limits.empty())
                throw std::invalid_argument(
                    "mootation: this run has " + std::to_string(g_problem->n_limits) +
                    " constraints but the seed population carries no per-constraint "
                    "values; pass seed_limits (minimize() recomputes them from "
                    "`constraints`)");
            opt.setup_with_seed(cfg.seed_variables, cfg.seed_objectives, {},
                                cfg.seed_limits);
        } else {
            opt.setup();
        }
        // the initial population is not offspring: the counts start here
        g_ops.setup_evals = g_ops.evals_read = g_evaluations.load();
        g_ops.rc_read = ops::repair_counts();
        const bool observe = cfg.on_generation && cfg.record_every > 0;
        auto one_step = [&]() {
            if (g_ops.on) ops_before_step(opt.get_vault());
            opt.step();
            if (g_ops.on) ops_after_step(opt.get_vault());
        };
        auto emit = [&](int g) {
            auto& v = opt.get_vault();
            std::size_t n = std::min<std::size_t>(
                v.active_n(), static_cast<std::size_t>(v.pop_size()));
            std::vector<std::vector<double>> P;
            P.reserve(n);
            for (std::size_t i = 0; i < n; ++i) P.push_back(v.objectives_of(i));
            py::gil_scoped_acquire gil;
            cfg.on_generation(g, std::move(P));
        };
        if (!by_evaluations) {
            if (observe) {
                emit(0);
                for (int g = 1; g <= cfg.n_gen; ++g) {
                    one_step();
                    if (g % cfg.record_every == 0 || g == cfg.n_gen) emit(g);
                }
            } else if (g_ops.on) {
                for (int g = 1; g <= cfg.n_gen; ++g) one_step();
            } else {
                opt.optimize(cfg.n_gen);
            }
        } else {
            if (observe) emit(0);
            const long long start  = g_evaluations.load();
            const long long stride = static_cast<long long>(cfg.record_every) *
                                     std::max(1, cfg.pop_size);
            long long next_record  = start + stride;
            long long idle         = 0;   // consecutive steps that evaluated nothing
            for (int g = 1; g_evaluations.load() < cfg.max_evaluations; ++g) {
                const long long before = g_evaluations.load();
                one_step();
                const long long now = g_evaluations.load();
                if (now > before) {
                    idle = 0;
                } else if (++idle >= 10000) {
                    throw std::runtime_error(
                        "mootation: 10000 steps in a row evaluated nothing; this core "
                        "cannot run on an evaluation budget, use n_gen");
                }
                if (g == 1) {
                    // The real cost of a step is known now: give the schedule the
                    // number of steps the budget buys (MOEA/D-AWA anneals over
                    // five times more steps than a generational core).
                    const long long per  = std::max(1LL, now - start);
                    const long long left = std::max(0LL, cfg.max_evaluations - now);
                    apply_t_max(alg, static_cast<int>(std::min<long long>(
                        INT_MAX, 1 + (left + per - 1) / per)));
                }
                const bool last = now >= cfg.max_evaluations;
                if (observe && (now >= next_record || last)) {
                    emit(g);
                    while (next_record <= now) next_record += stride;
                }
            }
        }
    }

    auto&    v = opt.get_vault();
    PyResult r;
    // NOT active_n(): steady-state cores (moead_de, moead_dd, hlmea, adaw,
    // ...) park a persistent scratch slot at active index pop_size(), so
    // active_n() is pop_size() + 1 for them. Returning that extra slot hands
    // the caller an unselected offspring dressed as a member of the answer
    // set — enough to skew any IGD or hypervolume computed from it, and
    // invisible unless you count the rows. See data_vault.hpp, "SCRATCH SLOTS
    // AND CONSUMERS".
    r.active_n = std::min<std::size_t>(v.active_n(),
                                       static_cast<std::size_t>(v.pop_size()));
    r.ignored  = std::move(ignored);
    r.evaluations = g_evaluations.load();
    for (const auto& u : ops::operators_used()) r.operators.emplace_back(u.op, u.repair);
    if (var_prob) {
        bool used = false;
        for (const auto& u : ops::operators_used()) used = used || std::string(u.op) == "sbx";
        if (!used) r.ignored.emplace_back("sbx_var_prob");
    }
    if (g_ops.on) {
        const auto& rc = ops::repair_counts();
        const double n_vars = static_cast<double>(g_problem->bounds.size());
        const double ev = static_cast<double>(r.evaluations - g_ops.setup_evals);
        r.operator_totals["offspring"] = static_cast<double>(g_ops.t_off);
        if (ev > 0) {
            r.operator_totals["oob_share"] = static_cast<double>(rc.out_children) / ev;
            r.operator_totals["oob_var_share"] = static_cast<double>(rc.out_vars) / (ev * n_vars);
        }
        if (g_ops.t_off > 0) {
            r.operator_totals["survival_share"] = static_cast<double>(g_ops.t_surv) / g_ops.t_off;
            r.operator_totals["offspring_nd_share"] = static_cast<double>(g_ops.t_nd) / g_ops.t_off;
        }
        if (g_ops.t_step_n > 0)
            r.operator_totals["step_mean"] = g_ops.t_step / static_cast<double>(g_ops.t_step_n);
    }
    r.objectives.reserve(r.active_n);
    r.variables.reserve(r.active_n);
    for (std::size_t i = 0; i < r.active_n; ++i) {
        r.objectives.push_back(v.objectives_of(i));
        r.variables.push_back(v.variables_of(i));
        r.cv.push_back(v.get_cv(i));
    }
    return r;
}

// ── Dispatch, generated from include/mootation/algorithms.def ───────────────────────────
PyResult run(const std::string& name, PyProblem& problem, const RunConfig& cfg)
{
    if (problem.bounds.empty())
        throw std::invalid_argument("problem.bounds is empty");

    g_problem = &problem;
    g_evaluations = 0;
    mootation::ops::reset_operator_records();
    g_ops = OpStats{};
    g_ops.on = cfg.operator_stats;
    struct Guard { ~Guard() { g_problem = nullptr; } } guard;

#define MOOTATION_ALG(KEY, IND, CORE) \
    if (name == #KEY) return run_core<PyTag_##KEY, mootation::CORE<PyTag_##KEY>>(cfg);
#include "mootation/algorithms.def"
#undef MOOTATION_ALG

    throw std::invalid_argument("unknown algorithm: " + name);
}

std::vector<std::string> algorithm_names()
{
    std::vector<std::string> v;
#define MOOTATION_ALG(KEY, IND, CORE) v.emplace_back(#KEY);
#include "mootation/algorithms.def"
#undef MOOTATION_ALG
    return v;
}

} // namespace

PYBIND11_MODULE(_core, m)
{
    m.doc() = "MOOtation — multi- and many-objective evolutionary algorithms";
    m.attr("__version__") = mootation::version();
    // The git revision this binary was built from (python/git_stamp.cmake);
    // "unknown" when built outside a git checkout or by another build system.
    m.attr("__git_commit__") = MOOTATION_GIT_COMMIT;
    m.attr("__git_dirty__")  = static_cast<bool>(MOOTATION_GIT_DIRTY);

    py::enum_<mootation::ConstraintMode>(m, "ConstraintMode")
        .value("NONE",           mootation::ConstraintMode::NONE)
        .value("FEASIBILITY",    mootation::ConstraintMode::FEASIBILITY)
        .value("EPS_CONSTRAINT", mootation::ConstraintMode::EPS_CONSTRAINT)
        .value("CDP",            mootation::ConstraintMode::CDP);

    py::class_<PyProblem>(m, "Problem")
        .def(py::init<>())
        .def_readwrite("bounds",         &PyProblem::bounds)
        .def_readwrite("n_objectives",   &PyProblem::n_objectives)
        .def_readwrite("n_limits",       &PyProblem::n_limits)
        .def_readwrite("evaluate",       &PyProblem::evaluate)
        .def_readwrite("evaluate_batch", &PyProblem::evaluate_batch)
        .def_readwrite("limits_batch",   &PyProblem::limits_batch);

    py::class_<RunConfig>(m, "Config")
        .def(py::init<>())
        .def_readwrite("pop_size",        &RunConfig::pop_size)
        .def_readwrite("n_gen",           &RunConfig::n_gen)
        .def_readwrite("seed",            &RunConfig::seed)
        .def_readwrite("constraint_mode", &RunConfig::constraint_mode)
        .def_readwrite("eta_c",           &RunConfig::eta_c)
        .def_readwrite("eta_m",           &RunConfig::eta_m)
        .def_readwrite("pc",              &RunConfig::pc)
        .def_readwrite("pm",              &RunConfig::pm)
        .def_readwrite("T",               &RunConfig::T)
        .def_readwrite("delta",           &RunConfig::delta)
        .def_readwrite("nr",              &RunConfig::nr)
        .def_readwrite("kappa",           &RunConfig::kappa)
        .def_readwrite("K",               &RunConfig::K)
        .def_readwrite("n_clusters",      &RunConfig::n_clusters)
        .def_readwrite("theta",           &RunConfig::theta)
        .def_readwrite("alpha",           &RunConfig::alpha)
        .def_readwrite("F",               &RunConfig::F)
        .def_readwrite("CR",              &RunConfig::CR)
        .def_readwrite("div",             &RunConfig::div)
        .def_readwrite("crossover",       &RunConfig::crossover,
                       "sbx (the default), uniform or blx_alpha: nsga2, ibea_eplus, "
                       "spea2_sde, agemoea")
        .def_readwrite("mutation",        &RunConfig::mutation,
                       "polynomial (the default), gaussian, cauchy, uniform_reset, mixture or "
                       "mixture_cauchy: the same four and moead_de")
        .def_readwrite("mutation_scale",  &RunConfig::mutation_scale,
                       "s of the gaussian (0.1) and Cauchy (0.05) steps, a share of ub - lb")
        .def_readwrite("mixture_q",       &RunConfig::mixture_q,
                       "the share of gaussian/Cauchy steps in a mixture (0.1)")
        .def_readwrite("blx_alpha",       &RunConfig::blx_alpha, "BLX-alpha's alpha (0.5)")
        .def_readwrite("sbx_var_prob",    &RunConfig::sbx_var_prob,
                       "SBX's share of crossed variables for this run (0.5, the canonical "
                       "realcross; 1.0 crosses every variable)")
        .def_readwrite("operator_stats",  &RunConfig::operator_stats,
                       "keep per-step operator statistics; read them with "
                       "operator_stats() from the on_generation observer")
        .def_readwrite("bound_repair",    &RunConfig::bound_repair,
                       "what an operator that can leave the box does with the variables "
                       "it put outside: clip, reflect, random, midpoint, resample, wrap, "
                       "native (operators/bound_repair.hpp)")
        .def_readwrite("normalize",       &RunConfig::normalize,
                       "the objective normalization of ibea_eplus, r2ibea, two_arch2 and "
                       "moead_am2m (their headers say which setting is the paper's)")
        .def_readwrite("seed_variables",  &RunConfig::seed_variables)
        .def_readwrite("seed_objectives", &RunConfig::seed_objectives)
        .def_readwrite("seed_limits",     &RunConfig::seed_limits)
        .def_readwrite("on_generation",   &RunConfig::on_generation,
                       "Observer called as on_generation(gen, objectives) every "
                       "record_every generations (gen 0 = after setup).")
        .def_readwrite("record_every",    &RunConfig::record_every,
                       "0 = no observer; k > 0 = call on_generation every k generations "
                       "(every k * pop_size evaluations under max_evaluations).")
        .def_readwrite("max_evaluations", &RunConfig::max_evaluations,
                       "0 = run n_gen steps; > 0 = step until this many evaluations are "
                       "spent (n_gen is then ignored).");

    py::class_<PyResult>(m, "Result")
        .def_readonly("objectives", &PyResult::objectives)
        .def_readonly("variables",  &PyResult::variables)
        .def_readonly("cv",         &PyResult::cv)
        .def_readonly("active_n",   &PyResult::active_n)
        .def_readonly("ignored",    &PyResult::ignored,
                      "Knobs you set that this algorithm does not have.")
        .def_readonly("evaluations", &PyResult::evaluations,
                      "Evaluations the run spent, setup included.")
        .def_readonly("operators", &PyResult::operators,
                      "(operator, bound repair) for every variation operator the run used")
        .def_readonly("operator_totals", &PyResult::operator_totals,
                      "the operator statistics over the whole run (operator_stats)");

    m.def("hypervolume",
          [](py::array_t<double, py::array::c_style | py::array::forcecast> points,
             py::array_t<double, py::array::c_style | py::array::forcecast> ref) {
              if (points.ndim() != 2)
                  throw std::invalid_argument("hypervolume: points must be a 2-D array");
              if (ref.ndim() != 1 || ref.shape(0) != points.shape(1))
                  throw std::invalid_argument(
                      "hypervolume: ref must have one value per objective (column)");
              const auto n = static_cast<std::size_t>(points.shape(0));
              const auto m = static_cast<std::size_t>(points.shape(1));
              const double* f = points.data();
              const double* r = ref.data();
              py::gil_scoped_release unlock;
              return mootation::hypervolume::wfg(f, n, m, r);
          },
          py::arg("points"), py::arg("ref"),
          "Exact hypervolume (minimisation) of the rows of `points` against `ref`, by "
          "the WFG algorithm (While, Bradstreet & Barone 2012). Rows not strictly "
          "better than `ref` in every objective, and rows with a NaN, add nothing.");
    m.def("hv_covered",
          [](py::array_t<double, py::array::c_style | py::array::forcecast> points,
             py::array_t<double, py::array::c_style | py::array::forcecast> samples) {
              if (points.ndim() != 2 || samples.ndim() != 2 ||
                  samples.shape(1) != points.shape(1))
                  throw std::invalid_argument(
                      "hv_covered: points and samples must be 2-D with the same columns");
              const auto n = static_cast<std::size_t>(points.shape(0));
              const auto k = static_cast<std::size_t>(samples.shape(0));
              const auto m = static_cast<std::size_t>(points.shape(1));
              const double* f = points.data();
              const double* s = samples.data();
              py::gil_scoped_release unlock;
              return mootation::hypervolume::covered(f, n, m, s, k);
          },
          py::arg("points"), py::arg("samples"),
          "How many rows of `samples` some row of `points` weakly dominates: the "
          "count behind a Monte-Carlo hypervolume estimate (minimisation).");
    m.def("operator_stats", []() {
              // Since the previous call: offspring evaluated, the shares of them
              // that left the box before repair (and of their variables), that
              // survived, that no parent dominates, and the mean step. None where
              // nothing was counted.
              py::dict d;
              const long long ev = g_evaluations.load() - g_ops.evals_read;
              const auto& rc = mootation::ops::repair_counts();
              const double n_vars = g_problem ? static_cast<double>(g_problem->bounds.size()) : 0.0;
              d["offspring"] = ev;
              if (ev > 0) {
                  d["oob_share"] = static_cast<double>(rc.out_children - g_ops.rc_read.out_children) / ev;
                  d["oob_var_share"] = n_vars > 0
                      ? py::cast(static_cast<double>(rc.out_vars - g_ops.rc_read.out_vars) / (ev * n_vars))
                      : py::none();
              } else {
                  d["oob_share"] = py::none();
                  d["oob_var_share"] = py::none();
              }
              if (g_ops.on && g_ops.off > 0) {
                  d["survival_share"] = static_cast<double>(g_ops.surv) / g_ops.off;
                  d["offspring_nd_share"] = static_cast<double>(g_ops.nd) / g_ops.off;
              } else {
                  d["survival_share"] = py::none();
                  d["offspring_nd_share"] = py::none();
              }
              d["step_mean"] = (g_ops.on && g_ops.step_n > 0)
                  ? py::cast(g_ops.step / static_cast<double>(g_ops.step_n)) : py::none();
              g_ops.evals_read = g_evaluations.load();
              g_ops.rc_read = rc;
              g_ops.off = g_ops.surv = g_ops.nd = g_ops.step_n = 0;
              g_ops.step = 0.0;
              return d;
          },
          "Operator statistics since the previous call, for the run in progress "
          "(call it from on_generation): offspring, oob_share, oob_var_share, "
          "survival_share, offspring_nd_share, step_mean. The last three need "
          "RunConfig.operator_stats.");
    m.def("algorithms", &algorithm_names,
          "Names accepted by run(), straight from include/mootation/algorithms.def.");
    m.def("run", &run, py::arg("name"), py::arg("problem"), py::arg("config"),
          "Run one algorithm and return its final population.");
}
