#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Flatten the library into a single header.

The library is already header-only, so this is a convenience, not a build step:
it produces one file you can drop into a project that has no include-path
control (a competition judge, a plugin SDK, a Compiler-Explorer link).

What it does, and equally what it does NOT do:

  * It resolves the project's own ``#include "..."`` graph depth-first and
    emits each file exactly once, so the result compiles standalone.
  * It hoists every ``#include <...>`` to the top, deduplicated. Standard
    headers must not be interleaved with library code, because the umbrella is
    tested to be self-contained when included first.
  * It does NOT reformat, minify, or strip comments. The header block of each
    algorithm is the artefact this project's fidelity claim rests on; a tool
    that dropped it would be deleting the documentation to save bytes.
  * It refuses to include anything matching ``*_local*``. Those are private and
    have leaked once before, through a path (the install glob) that the
    git-based guards did not cover. This is a third, independent check.

Usage:
    python tools/amalgamate.py                     # -> mootation_single.hpp
    python tools/amalgamate.py -o /tmp/os.hpp
    python tools/amalgamate.py --check             # verify it is reproducible
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INCLUDE_ROOT = ROOT / "include"
# Two entry points, in this order: the umbrella (every algorithm and every
# support header) and the embedding layer. embed.hpp is not part of the
# umbrella on purpose — it instantiates the run-time dispatch over all 60
# algorithms, and a program that names its algorithm at compile time should not
# pay for that. The single-header build is the opposite trade: one file, batteries
# included, so it carries embed.hpp too.
ENTRIES = [
    INCLUDE_ROOT / "mootation" / "mootation.hpp",
    INCLUDE_ROOT / "mootation" / "embed.hpp",
]

LOCAL_INCLUDE = re.compile(r'^\s*#\s*include\s*"([^"]+)"')
SYSTEM_INCLUDE = re.compile(r"^\s*#\s*include\s*<([^>]+)>")
PRAGMA_ONCE = re.compile(r"^\s*#\s*pragma\s+once\s*$")
SPDX = re.compile(r"^\s*//\s*SPDX-License-Identifier:")

BANNER = """// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// MOOtation — single-header amalgamation.
//
// GENERATED by tools/amalgamate.py. Do not edit: edit the sources under
// include/mootation/ and regenerate, or your change is lost on the next run.
//
// This is the same code as the normal include tree, concatenated in dependency
// order with the standard-library includes hoisted to the top. Every algorithm
// keeps its full header block — the paper it follows, the paper's defaults with
// the section they come from, and its declared deviations — because that
// documentation is the point of the library, not overhead.
// ============================================================================
"""


def is_private(path: Path) -> bool:
    return "_local" in path.as_posix()


def emit(path: Path, seen: set[Path], system: set[str], out: list[str]) -> None:
    """Depth-first: a file's own includes are emitted before the file itself."""
    path = path.resolve()
    if path in seen:
        return
    if is_private(path):
        raise SystemExit(f"refusing to amalgamate a private file: {path}")
    seen.add(path)

    body: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if PRAGMA_ONCE.match(line):
            continue
        if SPDX.match(line):
            continue  # one SPDX line at the top of the output is enough

        m = SYSTEM_INCLUDE.match(line)
        if m:
            system.add(m.group(1))
            continue

        m = LOCAL_INCLUDE.match(line)
        if m:
            target = (path.parent / m.group(1)).resolve()
            if not target.exists():
                # An include spelled relative to the include ROOT rather than to
                # the including file — "mootation/algorithms.def" from inside
                # mootation/. Both spellings work for the compiler because
                # include/ is on the search path, so both must work here.
                target = (INCLUDE_ROOT / m.group(1)).resolve()
            if not target.exists():
                raise SystemExit(f"{path}: cannot resolve #include \"{m.group(1)}\"")
            if target.suffix == ".def":
                # X-macro list: included many times with a different macro
                # definition each time, so it must be pasted at EVERY use.
                # Deduplicating it would silently drop all but the first
                # expansion and leave the dispatch missing 59 algorithms.
                if is_private(target):
                    raise SystemExit(f"refusing to amalgamate a private file: {target}")
                for defline in target.read_text(encoding="utf-8").splitlines():
                    if SPDX.match(defline):
                        continue
                    body.append(defline)
                continue
            emit(target, seen, system, out)
            continue

        body.append(line)

    rel = path.relative_to(INCLUDE_ROOT).as_posix()
    out.append(f"// ─── {rel} " + "─" * max(0, 70 - len(rel)))
    out.append("\n".join(body).rstrip())
    out.append("")


def build() -> str:
    seen: set[Path] = set()
    system: set[str] = set()
    body: list[str] = []
    for entry in ENTRIES:
        emit(entry, seen, system, body)

    parts = [BANNER, "#pragma once", ""]
    parts += [f"#include <{h}>" for h in sorted(system)]
    parts += ["", ""]
    parts += body
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--output", default=str(ROOT / "mootation_single.hpp"))
    ap.add_argument(
        "--check",
        action="store_true",
        help="do not write; fail if the output would differ from the file on disk",
    )
    args = ap.parse_args()

    text = build()
    dest = Path(args.output)

    if args.check:
        if not dest.exists():
            print(f"{dest} does not exist; run tools/amalgamate.py", file=sys.stderr)
            return 1
        if dest.read_text(encoding="utf-8") != text:
            print(f"{dest} is stale; regenerate with tools/amalgamate.py", file=sys.stderr)
            return 1
        print(f"{dest} is up to date")
        return 0

    dest.write_text(text, encoding="utf-8", newline="\n")
    lines = text.count("\n")
    print(f"wrote {dest} ({lines} lines, {len(text) // 1024} KiB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
